Repository Financial-Times/origami-ci-tools, pull requests merged in 2020-09, with the labels that each got.

#75 build(deps): npm audit fix
  package-lock.json
Labels: cli, dependencies, security

#79 upgrade occ version
  package.json
Labels: cli, release:minor

#80 upgrade occ version
  package.json
Labels: cli, release:patch
