Repository Financial-Times/origami-ci-tools, pull requests merged in 2020-05, with the labels that each got.

#54 Upgrade to origami-build-tools v10.
  MIGRATION.md
  README.md
  package.json
Labels: breaking, release:major

#55 Install at least origami-build-tools@10.1.8
  package.json
Labels: release:patch

#60 Make a special case for ftdomdelegate as it is not published under a namespace
  commands/branch.js
Labels: release:patch

#62 Add Github Action to apply Origami type label
  .github/workflows/apply-labels.yml
Labels: cli
