Repository Financial-Times/origami-ci-tools, pull requests merged in 2021-01, with the labels that each got.

#98 Create the prefix directory if it doesn't exist
  lib/install-dependencies.js
Labels: cli, release:minor

#101 Fix conflicts
  .github/workflows/automatic-tag-and-release.yml
Labels: cli, release:beta

#102 Use the latest origami build tools beta
  package.json
Labels: cli, release:beta

#103 Add ability to publish prereleases with a different dist-tag.
  .github/workflows/automatic-tag-and-release.yml
  .github/workflows/publish-to-npm-as-latest.yml
  .github/workflows/publish-to-npm-as-prerelease.yml
Labels: cli

#105 Bump obt beta
  package.json
Labels: cli, release:beta
